In [1]:
import numpy as np

In [2]:
rows = int(input("Enter no of rows: "))
cols = int(input("Enter no of cols: "))

Enter no of rows:  3
Enter no of cols:  3


In [13]:
print("Enter matrix1 contents: ")
matrix1 = []
for i in range(rows*cols):
    matrix1.append(int(input()))

matrix1 = np.array(matrix1).reshape(rows, cols)
matrix1

Enter matrix1 contents: 


 1
 2
 3
 4
 5
 6
 70
 80
 90


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [70, 80, 90]])

In [14]:
print("Enter matrix2 contents: ")
matrix2 = []
for i in range(rows*cols):
    matrix2.append(int(input()))

matrix2 = np.array(matrix2).reshape(rows, cols)
matrix2

Enter matrix2 contents: 


 1
 2
 3
 4
 5
 6
 7
 8
 9


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
matrix_add = np.add(matrix1, matrix2)
matrix_add

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [77, 88, 99]])

In [16]:
matrix_mul = np.matmul(matrix1, matrix2)
matrix_mul

array([[  30,   36,   42],
       [  66,   81,   96],
       [1020, 1260, 1500]])

In [17]:
matrix1_transpose = matrix1.T
matrix1_transpose

array([[ 1,  4, 70],
       [ 2,  5, 80],
       [ 3,  6, 90]])

In [18]:
matrix1_inv = np.linalg.inv(matrix1)
matrix1_inv

LinAlgError: Singular matrix