# Matrix Operations

* Matrix creation using numpy arrays
* Matrix addition and multiplication using coding and built in functions: matmul, matrix transpose, matrix inversion


In [2]:
import numpy as np

In [3]:
matrix1 = np.array(np.arange(1, 10)).reshape(3, 3)
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
matrix2 = np.array(np.arange(11, 20)).reshape(3, 3)
matrix2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### Matrix Addition and Multiplication using coding

In [10]:
# Matrix Addition

added_matrix = []
for i in range(len(matrix1)):
    for j in range(len(matrix1)):
        added_matrix.append(matrix1[i][j] + matrix2[i][j]);
added_matrix = np.array(added_matrix).reshape(3, 3)
added_matrix

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [11]:
# Matrix Multiplication

multiplied_matrix = []
for i in range(len(matrix1)):
    for j in range(len(matrix2)):
        multiplied_matrix.append(matrix1[i][j] * matrix2[i][j])
multiplied_matrix = np.array(multiplied_matrix).reshape(3, 3)
multiplied_matrix

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

### Matrix Addition and Multiplication using In-Built functions

In [12]:
# Matrix Addition

add_matrix = np.add(matrix1, matrix2)
add_matrix

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [13]:
mul_matrix = np.matmul(matrix1, matrix2)
mul_matrix

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

### Matrix Transpose and Matrix Inversion

In [18]:
matrix = np.arange(20, 50).reshape(3, 10)
matrix

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
# Transpose

transpose_matrix = matrix.T
transpose_matrix

array([[20, 30, 40],
       [21, 31, 41],
       [22, 32, 42],
       [23, 33, 43],
       [24, 34, 44],
       [25, 35, 45],
       [26, 36, 46],
       [27, 37, 47],
       [28, 38, 48],
       [29, 39, 49]])

In [26]:
# Inversion

new_matrix = [3, 2, 7, 10, 5, 22, 90, 43, 1]
new_matrix = np.array(new_matrix).reshape(3, 3)
inverted_matrix = np.linalg.inv(new_matrix)
inverted_matrix

array([[-0.96315251,  0.30603889,  0.00921187],
       [ 2.01637666, -0.64176049,  0.00409417],
       [-0.02047083,  0.05220061, -0.00511771]])