# Practice Lab

### range and arange()

In [6]:
print([x for x in range(10)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
print([x for x in range(1,10)])

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
print([x for x in range(1,10,2)])

[1, 3, 5, 7, 9]


In [10]:
import numpy as np

In [18]:
range_val = np.array(np.arange(1,10))
print(range_val)
print(range_val.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [22]:
new_range_val = np.array(np.arange(2, 10, 3, dtype='int64'))

In [23]:
new_range_val

array([2, 5, 8], dtype=int64)

### Random

In [56]:
import random

state = random.getstate()
random.setstate(state)

In [61]:
#This method returns a random floating number between 0 and 1.
print(random.random())

0.9212677514042844


In [62]:
# Generating a random number from a given interval

print(random.randint(20, 50))

43


In [65]:
# Generates n no. of random numbers and returns as a list from a given interval
sample_list = random.sample(range(20, 50), 6)
sample_list

[29, 26, 33, 25, 49, 41]

In [66]:
# choice() - to select a random number/choice from a given range of values

print(random.choice([1,4,6,200]))

6


In [67]:
# Creating an array of random numbers

np.random.rand(3,2)

array([[0.88134711, 0.57155074],
       [0.56300137, 0.45143806],
       [0.05803657, 0.4342372 ]])

In [72]:
np.random.randint(10, size=(3,3))

array([[2, 2, 4],
       [7, 2, 5],
       [5, 9, 5]])

### Matrix Ops

In [83]:
import numpy as np

rows = int(input("Enter no. of rows:"))
cols = int(input("Enter no. of cols:"))

total = rows * cols

num1 = []
for i in range(total):
    data = int(input())
    num1.append(data)

matrix1 = np.array(num1)
matrix1 = matrix1.reshape(rows,cols)

Enter no. of rows:3
Enter no. of cols:3
1
2
3
4
5
6
7
8
9


In [84]:
num2 = []
for i in range(total):
    data = int(input())
    num2.append(data)

matrix2 = np.array(num2)
matrix2 = matrix2.reshape(rows,cols)

3
2
1
6
5
4
9
8
7


In [88]:
multiply = np.matmul(matrix1, matrix2)
multiply

array([[ 42,  36,  30],
       [ 96,  81,  66],
       [150, 126, 102]])

In [94]:
# dot product

dot_multiply = np.dot(matrix1, matrix2)
dot_multiply

array([[ 42,  36,  30],
       [ 96,  81,  66],
       [150, 126, 102]])

In [95]:
_multiply = matrix1 @ matrix2
_multiply

array([[ 42,  36,  30],
       [ 96,  81,  66],
       [150, 126, 102]])

In [96]:
matrix_transpose = multiply.T
matrix_transpose

array([[ 42,  96, 150],
       [ 36,  81, 126],
       [ 30,  66, 102]])

In [104]:
np.linalg.det(multiply)

0.0

# HW - Explore tabulate package